controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\User;
use app\models\Recruit;
use yii\web\UploadedFile;


class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [

            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login','logout'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login'],
                        'roles' => ['?'],
                    ],
                    
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['get'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->layout = 'main';
        return $this->render('index');
    }

    
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post())) {
            if($model->login()){
                return $this->redirect(['user/user-homepage']);
            }
        }
        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }
    
    public function actionRegister()
    {
        $model = new User;
        if ($model->load(Yii::$app->request->post())) {

            // get the instance varibale of file......
            $imageName = 'Resume'.rand(10,100).'_'.$model->name;
            $model->file = UploadedFile::getInstance($model , 'file');

            if($model->file){
                $imageName = $imageName.'.'.$model->file->extension;
                $model->resume = $imageName;
                $model->file->saveAs('../web/resume/'.$imageName);
            }

            $model->authKey = md5($model->password);
            $model->password = password_hash($model->password, PASSWORD_DEFAULT);

            if($model->save()){
                return $this->redirect(['employement-detail/create']);
            }            
        }else{
            return $this->render('register', [
                'model' => $model,
            ]);
        }
    }
    

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }


    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }


// ************************************************************************************************
    // Get dependendlist For District Block Village
    public function actionLists()
    {
        $post = Yii::$app->request->post();
        if($post['type'] == 1){
            $query = new \yii\db\Query;
                     $query->select(['state_id','name'])  
                           ->from('state')
                           ->where(['country_id' => $post['id']]);
            $command = $query->createCommand();
            $operations = $command->queryAll();
            return json_encode($operations); 
        }

        if($post['type'] == 6){
            $query = new \yii\db\Query;
                     $query->select(['city_id','name'])  
                           ->from('city')
                           ->where(['country_id' => $post['id']]);
            $command = $query->createCommand();
            $operations = $command->queryAll();
            return json_encode($operations); 
        }
         
        if($post['type'] == 2) {
            $query = new \yii\db\Query;
                     $query->select(['id','rpc_name'])  
                           ->from('rpc_centre')
                           ->where(['district_id' => $post['id']]);
            $command = $query->createCommand();
            $operations = $command->queryAll();
            return json_encode($operations); 
      }
        if($post['type'] == 3){
            $query = new \yii\db\Query;
                     $query->select(['id','sub_cat_name'])  
                           ->from('sub_category')
                           ->where(['category_id' => $post['id']]);
            $command = $query->createCommand();
            $operations = $command->queryAll();
       
            return json_encode($operations); 
        }

         if($post['type'] == 4){
            $query = new \yii\db\Query;
                     $query->select(['id','name'])  
                           ->from('sub_sub_category')
                           ->where(['sub_cat_id' => $post['id']]);
            $command = $query->createCommand();
            $operations = $command->queryAll();
       
            return json_encode($operations); 
        }
        if($post['type'] == 5){
            $query = new \yii\db\Query;
                     $query->select(['id','sub_cat_name'])  
                           ->from('sub_category')
                           ->where(['category_id' => $post['id']]);
            $command = $query->createCommand();
            $operations = $command->queryAll();
            return json_encode($operations); 
        }


    }
    

    // Get Dependent List when update 

    public function actionGetDependentLists()
    {
       if ($id = Yii::$app->request->post('id')) {
                $operationPosts = \app\models\Nandghar::find()
                    ->where(['village_id' => $id])
                    ->count();
                if ($operationPosts > 0) {
                $query = new \yii\db\Query;
                $query->select(['village.id as villageId',
                                'district.id as districtId',
                                'block.id as blockId',
                                'state.id as stateId'
                               ])  
                ->from('state')
                ->innerJoin("district","district.state_id = state.id")
                ->innerJoin("block","block.district_id = district.id")
                ->innerJoin("village","village.block_id = block.id")
                ->where(['village.id' => $id]);
                $command = $query->createCommand();
                $operations = $command->queryAll();
                return json_encode($operations);
                    
            }
        }
    }

}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/login(copy).php
<?php

use app\assets\loginAsset;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';

?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = 'Login';

?>

<style type="text/css">
    .form-horizontal .control-label {
        display: none;
    }
    .form-control {
        margin-left: 80px;
        width: 150%;
        height: 41px; 
    }

    .btn {
        height: 50px;
        width: 400px;
    }
    .has-error .help-block, .has-error .control-label, .has-error .radio, .has-error .checkbox, .has-error .radio-inline, .has-error .checkbox-inline, .has-error.radio label, .has-error.checkbox label, .has-error.radio-inline label, .has-error.checkbox-inline label {
        color: #a94442;
        margin-left: 80px;
    }
    
    label {
        display: inline-block;
        max-width: 100%;
        margin-bottom: 5px;
        font-weight: 100;
        font-size: small;
    }
    .has-error .help-block, .has-error .control-label, .has-error .radio, .has-error .checkbox, .has-error .radio-inline, .has-error .checkbox-inline, .has-error.radio label, .has-error.checkbox label, .has-error.radio-inline label, .has-error.checkbox-inline label {
        color: #cc2623;
        margin-left: 85px;
        width: 300px;
        font-size: 13px;
    }
    a{
      color: #79B9CF;
    }

</style>

<div class="site-login">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body" style="text-align:left;"> 
        <h4 style="margin-left: 35px; "><b>Login</b></h4><br>
          <?php $form = ActiveForm::begin([
            'id' => 'login-form',
            'layout' => 'horizontal',
            'enableAjaxValidation' => false
          ]); ?>
        
          <label style="margin-left: 80px">Email ID/Username<span style="color: red">*</span></label>

          <?= $form->field($model, 'email')->textInput(array('placeholder' => 'Username or email')); ?>
        
          <label style="margin-left: 80px">Password<span style="color: red">*</span></label>

          <?= $form->field($model, 'password')->passwordInput(array('placeholder' => 'Password'))->label('Password<span>*</span>'); ?>
                
          <p style="margin-left: 80px; ">
            <?= Html::a('Forget password?', ['site/request-password-reset'],['target'=>'_blank']) ?>
          </p> <br><br>          

          <div class="form-group" style="margin-left: 80px">
              <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
          </div>
 
          <p class="register" style="margin-left: 150px;">
              Not a member as yet?<?= Html::a('Register Now', ['site/register'],['target'=>'_blank']) ?>
          </p>
 
        <?php ActiveForm::end(); ?>
 
      </div>
    </div>
  </div>
</div>

views/site/register.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
// use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\UserLevel;

$this->title = 'Register';

?>

<style type="text/css">
    .form-horizontal .control-label {
        display: none;
    }
    .form-control {
        margin-left: 80px;
        width: 150%;
        height: 41px; 
    }

    .btn {
        height: 50px;
        width: 400px;
    }
    .has-error .help-block, .has-error .control-label, .has-error .radio, .has-error .checkbox, .has-error .radio-inline, .has-error .checkbox-inline, .has-error.radio label, .has-error.checkbox label, .has-error.radio-inline label, .has-error.checkbox-inline label {
        color: #a94442;
        margin-left: 80px;
    }
    
    label {
        display: inline-block;
        max-width: 100%;
        margin-bottom: 5px;
        font-weight: 100;
        font-size: small;
    }
    .has-error .help-block, .has-error .control-label, .has-error .radio, .has-error .checkbox, .has-error .radio-inline, .has-error .checkbox-inline, .has-error.radio label, .has-error.checkbox label, .has-error.radio-inline label, .has-error.checkbox-inline label {
        color: #cc2623;
        margin-left: 85px;
        width: 300px;
        font-size: 13px;
    }
    a{
      color: #79B9CF;
    }
    input[type="file"] {
        display: block;
        margin-left: 80px;
        background-color: white;
    }

</style>

<div class="site-login">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body" style="text-align:left;"> 
            <h4 style="margin-left: 35px; "><b>Login</b></h4><br>
              <?php $form = ActiveForm::begin([
                'options'=> ['enctype' => 'multipart/form-data'],
                'id' => 'login-form',
                'layout' => 'horizontal',
                'enableAjaxValidation' => false
            ]); ?>

            <label style="margin-left: 80px">Name<span style="color: red">*</span></label>
            <?= $form->field($model, 'name')->textInput(['maxlength' => true,'autofocus' => true,'autocomplete'=>"off"]) ?>

            <label style="margin-left: 80px">Email ID<span style="color: red">*</span></label>
             <?= $form->field($model, 'email')->textInput(array('placeholder' => 'Username or email')); ?>
            
            <label style="margin-left: 80px">Create Password<span style="color: red">*</span></label>
            <?= $form->field($model, 'password')->passwordInput(array('placeholder' => 'Enter password')) ?>
           
            <label style="margin-left: 80px">Mobile Number<span style="color: red">*</span></label>
            <?= $form->field($model, 'mobile')->textInput(['maxlength' => true,'placeholder'=>'Enter mobile number']) ?>
            <label style="margin-left: 80px">Total Work Experience<span style="color: red">*</span></label>

            <div class="row">
    
            <div class="col-md-5">      

            <?php 
            $workexp = array(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20);

            echo $form->field($model, 'total_work_experience')->dropDownList($workexp,
                [
                    'prompt'=>'Years'
                ]) 
            ?>
            </div>
            <div class="col-md-5">

                <?php 
                $month = array(0,1,2,3,4,5,6,7,8,9,10,11,12);

                echo $form->field($model, 'month')->dropDownList($month,
                    [
                        'prompt'=>'Month'
                    ]) 
                ?>
            </div>
            </div>
            
            <label style="margin-left: 80px">Resume<span style="color: red">*</span></label>
            <?= $form->field($model, 'file')->fileInput(); ?>
       
            <div class="form-group" style="margin-left: 80px">
              <?= Html::submitButton('Register', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>                     
            
        </div>
    </div>
  </div>
</div>